Sprint 3 Tarea 4

In [3]:
#Ejercicio 1
import numpy as np
array1= np.array([1, 2, 3, 4, 5, 10])
if array1.ndim > 1:
    print ("Error. Su array tiene mas de una dimension!")
else:
    print("Minimo: ", array1.min())
    print("Maximo: ", array1.max())
    print("Promedio: ", array1.mean())
    print("Deviacion estandar: ", np.std(array1))

Minimo:  1
Maximo:  10
Promedio:  4.166666666666667
Deviacion estandar:  2.91070819942883


In [4]:
#Ejercicio 2
num= int(input())
array2= np.random.randint(101, size=(num,num))
print(array2)

3
[[33  7 58]
 [92  7 21]
 [74 41 53]]


In [5]:
#Ejercicio 3
array3= np.array([[1, 2, 3, 4, 5, 22],[0, 2, 3, 4, 5, 1]])
print(array3.ndim)
print(array3)
print(np.sum(array3, axis = 0))#totales por columna
#columna 0= 1, columna 1= 4, etc

print(np.sum(array3, axis=1))#totales por fila
#fila 0= 37, fila 1= 15

2
[[ 1  2  3  4  5 22]
 [ 0  2  3  4  5  1]]
[ 1  4  6  8 10 23]
[37 15]


In [6]:
#Ejercicio 4
peso=[60, 62, 70, 90, 83, 75]
altura=[152, 155, 160, 190, 190, 189]
cov_mat = np.stack((peso, altura), axis = 0)
print(np.cov(cov_mat))

[[138.26666667 200.33333333]
 [200.33333333 353.46666667]]


In [11]:
coeficiente_correlacion= np.cov(cov_mat)[0][1]/(((np.cov(cov_mat)[0][0])**0.5)*((np.cov(cov_mat)[1][1])**0.5))
print(coeficiente_correlacion)

0.9061920308208827


In [4]:
#mismo ejercicio usando funcion
def coeficiente_correlacion(a, b):
    cov_matriz = np.stack((a, b), axis = 0)
    np.cov(cov_matriz)
    R = np.cov(cov_matriz)[0][1] / (np.std(a) * np.std(b))
    return R

In [5]:
peso1=[60, 62, 70, 90, 83, 75]
altura1=[152, 155, 160, 190, 190, 189]
print(coeficiente_correlacion(peso1, altura1)) #no sé por qué me sale un resultado diferente?

1.0874304369850596
